config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#top'
   resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to @book
    else
      @books = Book.all
      render :index
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to @book
  end


  private

  def set_book
    @book = Book.find(params[:id])

  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<%= form_with model: @book do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
 <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2

  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
 </div>
 <% end %>

 <h4>Title</h4>
 <%= f.text_field :title, class: "book_title" %>

 <h4>Body</h4>
 <%= f.text_area :body, class: "body_class" %>

 <p><%= f.submit 'Update Book' %></p>

 <td><%= link_to 'Show', book_path(@book), class: "show_#{@book.id}" %></td>
 <td><%= link_to 'Back', books_path, class: "back" %></td>

 <% end %>

app/views/books/index.html.erb
<main>

<div>
 <%= flash[:notice] %>
</div>

<h1>Books</h1>


<table>
 <thead>
 <tr>
  <th>Title</th>
  <th>Body</th>
  <th colspan="3"></th>
 </tr>
 </thead>

 <tbody>
<% @books.each do |book| %>
<tr>
 <td><%= book.title %></td>
 <td><%= book.body %></td>
 <td>
     <%= link_to "Show", book_path(book), class: "show_#{book.id}" %>
     <%= link_to "Edit", edit_book_path(book), class: "edit_#{book.id}" %>
     <%= link_to "Destroy", book_path(book), method: :delete, class: "destroy_#{book.id}" %>
 </td>
</tr>

<% end %>
</tbody>
</table>



<h1>New Book</h1>


<%= form_with model: @book do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
 <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
 </div>
 <% end %>

  <h4 class="form_field">Title</h4>
  <%= f.text_field :title, class: "book_title" %>
  <h4 class="form_field">Body</h4>
  <%= f.text_area :body, class: "book_body" %>
  <p><%= f.submit 'Create Book' %></p>

<% end %>

</main>

app/views/books/new.html.erb
<h1>New Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4 class="form_field">Title</h4>
  <%= f.text_field :title, class: "book_title" %>
  <h4 class="form_field">Body</h4>
  <%= f.text_area :body, class: "book_body" %>
  <p><%= f.submit 'Create Book' %></p>

<% end %>

app/views/books/show.html.erb
<main>

<% if flash[:notice] %>
<div class="notice">
  <%= flash[:notice] %>
</div>
<% end %>

<p><strong>Title:</strong>
   <%= @book.title %>
</p>

<p><strong>Body:</strong>
   <%= @book.body %>
</p>


    <%= link_to 'Edit', edit_book_path(@book), class: "edit_#{@book.id}" %>
    <%= link_to 'Back', books_path, class: "back" %>

</main>

app/views/homes/top.html.erb
<main>
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます.</p>

<a href="/books">start</a>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>